name: Java CI con Maven

on:
  push:
    branches: [ "master", "main" ] # Se activa al subir código a estas ramas

jobs:
  build:
    runs-on: ubuntu-latest # El robot usa un ordenador con Linux

    steps:
    - uses: actions/checkout@v4 # 1. Descarga tu código
    
    - name: Set up JDK 17 # 2. Instala Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven # 3. Compila y pasa los tests
      run: mvn -B package --file pom.xml